digraph tree {
  1 -> null_0;
  null_0 [shape="point", color="red"];
  1 -> 2;
  2 -> null_1;
  null_1 [shape="point", color="red"];
  2 -> 3;
  3 -> null_2;
  null_2 [shape="point", color="red"];
  3 -> f;
  f -> null_3;
  null_3 [shape="point", color="red"];
  f -> s;
  s -> h;
  s -> null_4;
  null_4 [shape="point", color="red"];
  h -> null_5;
  null_5 [shape="point", color="red"];
  h -> null_6;
  null_6 [shape="point", color="red"];
}
