#ifndef ERR_H__
#define ERR_H__

#define ERR_OK 0
#define ERR_OPERATION 1
#define ERR_STATIC_STACK_OVERFLOW 2
#define ERR_STATIC_STACK_UNDERFLOW 3
#define ERR_STRING 4
#define ERR_STRING_OVERFLOW 5
#define ERR_MEMORY_ALLOCATION 6

#endif
